personaldashboard/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path('login/', TemplateView.as_view(template_name="login/index.html")),
    path('', include('todo.urls')),
    # path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo_list'
urlpatterns = [
    path('', views.ToDoListView.as_view(), name='todo_list'),
    path('notes/', views.save_notes, name='notes'),
    path('<int:pk>/', views.EditToDo.as_view(), name='detail'),
    path('completed/', views.CompletedView.as_view(), name='completed'),
    path('<int:todo_item_id>/complete_todo/',
         views.complete_todo, name="complete_todo"),
    path('add_todo_item/', views.AddToDoItemView.as_view(), name='add_todo_item'),
    path('delete_todo_item/<int:todo_item_id>/',
         views.delete_todo, name='delete_todo_item'),
    path('<int:todo_item_id>/change_all/', views.change_all, name='change_all'),
    path('add_todo_item/<int:todo_item_id>/create_recurrences/',
         views.create_recurrences, name='create_recurrences'),

    path('day/', views.DayView.as_view(), name='day'),
    path('day/<int:year>/<str:month>/<int:day>/',
         views.SpecificDayView.as_view(), name='specific_day'),
    path('today/', 
          views.TodoTodayArchiveView.as_view(), name='archive_today'),
    path('<int:todo_item_id>/edit_recurrences/',
         views.edit_recurrences, name='edit_recurrences'),
    path('<int:todo_item_id>/add_subtask/',
         views.create_subtask_model_form, name='add_subtask'),
    path('<int:subtask_id>/complete_subtask/',
         views.complete_subtask, name='complete_subtask'),

    path('week/', views.WeekView.as_view(), name='week'),
    path('<int:year>/week/<int:week>/', views.SpecificWeekView.as_view(), name='specific_week'),

    path('month/', views.MonthView.as_view(), name='month'),
    path('month/<int:year>/<str:month>/', views.month_calendar_view, name='specific_month'),
    path('next_month/<int:year>/<str:month>/', views.month_calendar_next, name='next_month'),
    path('prev_month/<int:year>/<str:month>/', views.month_calendar_prev, name='prev_month'),

    path('job/', views.JobListView.as_view(), name='job_list'),
    path('job/today/', views.JobTodayList.as_view(), name='job_today_todo_list'),
    path('social/', views.SocialListView.as_view(), name='social_list'),
    path('social/today/', views.SocTodayList.as_view(), name='social_today_todo_list'),
    path('personal/', views.PersonalListView.as_view(), name='personal_list'),
    path('personal/today/', views.PersonalTodayList.as_view(), name='personal_today_todo_list'),
    path('other/', views.OtherListView.as_view(), name='other_list'),
    path('other/today/', views.OtherTodayList.as_view(), name='other_today_todo_list'),

    path('academics/', views.AcademicsListView.as_view(), name='academics_list'),
    path('academics/today/', views.AcademicsListTodayView.as_view(), name='academics_today_todo_list'),
    path('add_course/', views.AddCourseView.as_view(), name='add_course'),
    path('your_courses/', views.CourseListView.as_view(), name='course_list'),
    path('course/<int:course_id>/delete_course/',
         views.delete_course, name='delete_course'),
    path('course/<int:pk>/edit_course/',
         views.EditCourseView.as_view(), name='edit_course'),

    path('extracurriculars/', views.ECToDoList.as_view(), name='ec_todo_list'),
    path('extracurriculars/today', views.ECTodayList.as_view(), name='ec_today_todo_list'),
    path('your_ec/', views.ECListView.as_view(), name='ec_list'),
    path('add_ec', views.AddEC.as_view(), name='add_ec'),
    path('ec/<int:pk>/edit_ec/', views.EditEC.as_view(), name='edit_ec'),
    path('ec/<int:ec_id>/delete_ec', views.delete_ec, name='delete_ec'),

    path('delete_all_completed/', views.delete_all_completed,
         name='delete_all_completed'),
    path('delete_all_incompleted/', views.delete_all_incompleted,
         name='delete_all_incompleted'),

]

todo/models.py
from django.contrib.auth.models import User
from django.db import models
import django.utils
from model_utils import FieldTracker
import datetime
# https://stackoverflow.com/questions/849142/how-to-limit-the-maximum-value-of-a-numeric-field-in-a-django-model
from django.core.validators import MaxValueValidator, MinValueValidator
# https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#arrayfield
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Course(models.Model):
    course_name = models.CharField(max_length=50, verbose_name='Course Name')
    course_abbrev = models.CharField(
        max_length=10, verbose_name='Course Abbreviation')
    course_prof = models.CharField(
        max_length=20, verbose_name='Course Professor')
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.course_name


class Extracurricular(models.Model):
    name = models.CharField(max_length=20, verbose_name="Name")
    detail = models.CharField(max_length=100, verbose_name='Details')
    start_date = models.DateField(
        default=datetime.date.today, blank=True, verbose_name='Start date')
    end_date = models.DateField(
        default=datetime.date.today, blank=True, verbose_name='End date')
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ToDoItem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    ec = models.ForeignKey(Extracurricular, on_delete=models.SET_NULL,
                           null=True, verbose_name='Extracurriculars')
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=600, blank=True, default="")
    duedate = models.DateTimeField(
        default=django.utils.timezone.now, blank=True)
    location = models.CharField(max_length=50, blank=True)
    completed = models.BooleanField(default=False)
    progress = models.IntegerField(default=0, validators=[MinValueValidator(
        0), MaxValueValidator(100)], verbose_name="Progress")

    # recurrence freq choices
    NEVER = 'NEVER'
    DAILY = 'DAILY'
    WEEKLY = 'WEEKLY'
    MONTHLY = 'MONTHLY'
    YEARLY = 'YEARLY'
    FREQ_CHOICES = [
        (NEVER, 'Never'),
        (DAILY, 'Daily'),
        (WEEKLY, 'Weekly'),
        (MONTHLY, 'Monthly'),
        (YEARLY, 'Yearly'),
    ]
    recur_freq = models.CharField(
        max_length=7,
        choices=FREQ_CHOICES,
        default=NEVER,
    )
    # customize day of week
    # every other day
    # every other week
    end_recur_date = models.DateTimeField(
        default=django.utils.timezone.now, blank=True)
    # end repeat date and time
    # end after a specific day
    # never
    # end after # occurrences

    # priority choices
    HIGH = 'HI'
    MEDIUM = 'MD'
    LOW = 'LO'
    PRIORITY_CHOICES = [
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High')
    ]
    priority = models.CharField(
        max_length=2,
        choices=PRIORITY_CHOICES,
        default=LOW,
    )

    # category choices
    CATEGORIES = [
        ('NN', 'None'),
        ('AC', 'Academics'),
        ('EC', 'Extracurriculars'),
        ('JB', 'Job'),
        ('SC', 'Social'),
        ('PS', 'Personal'),
        ('OT', 'Other')
    ]
    category = models.CharField(
        max_length=2,
        choices=CATEGORIES,
        default='NN',
        verbose_name='Category',
    )

    has_title_changed = models.BooleanField(default=False)
    has_description_changed = models.BooleanField(default=False)
    has_duedate_changed = models.BooleanField(default=False)
    has_location_changed = models.BooleanField(default=False)
    has_recur_freq_changed = models.BooleanField(default=False)
    has_end_recur_date_changed = models.BooleanField(default=False)
    has_category_changed = models.BooleanField(default=False)
    has_priority_changed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    # array storing id of future events associated with current object
    future_events = ArrayField(models.IntegerField(
        default=0), default=list, null=True)
    number_of_subtasks = models.IntegerField( default=0 )

    # https://stackoverflow.com/questions/36617145/django-arrayfield-null-true-migration-with-postgresql
    tracker = FieldTracker()  # track changes to fields

    def __str__(self):
        return self.title + " " + self.duedate.strftime('%Y-%m-%d')

    def is_past_due(self):
        now = django.utils.timezone.now()
        return now > self.duedate

    def is_today_duedate(self):
        now = django.utils.timezone.now()
        due = self.duedate
        is_same = (now.day == due.day and now.month == due.month and now.year == due.year)
        return is_same


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField()


class SubTask(models.Model):
    todo = models.ForeignKey(ToDoItem, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    detail = models.CharField(max_length=200, blank=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.detail

todo/forms.py
from .models import ToDoItem, Course, Extracurricular, SubTask
from django.template.defaultfilters import mark_safe
from django.utils import timezone
from django import forms
# https://pypi.org/project/django-tempus-dominus/
from tempus_dominus.widgets import DateTimePicker, DatePicker
import datetime
from datetime import date
from django.forms import modelformset_factory


class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ['title', 'description', 'duedate', 'location', 'recur_freq',
                  'end_recur_date', 'priority', 'category', 'course', 'ec', 'progress']
        labels = {'recur_freq': mark_safe('Repeat'), 'end_recur_date': mark_safe(
            'End repeat'), 'duedate': mark_safe('Due Date'), }  # label and bold it
        widgets = {'description': forms.Textarea(attrs={'cols': 35, 'rows': 5}),
                   'duedate': DateTimePicker(attrs={'placeholder': 'yyyy-mm-dd HH:MM',
                                                    'append': 'fa fa-calendar',
                                                    'icon_toggle': True, },
                                             options={'useCurrent': True,
                                                      'collapse': True, }
                                             ),
                   'end_recur_date': DateTimePicker(attrs={'placeholder': 'yyyy-mm-dd HH:MM',
                                                           'append': 'fa fa-calendar',
                                                           'icon_toggle': True, },
                                                    options={'useCurrent': True,
                                                             'collapse': True, }
                                                    ),
                   }

    def filter_course_and_ec(self, user=None):
        if user:
            self.fields['course'].queryset = Course.objects.filter(
                user=user)
            self.fields['ec'].queryset = Extracurricular.objects.filter(
                user=user)
        else:
            self.fields['course'].queryset = Course.objects.filter(
                user__isnull=True)
            self.fields['ec'].queryset = Extracurricular.objects.filter(
                user__isnull=True)


class SubTaskForm(forms.ModelForm):
    class Meta:
        model = SubTask
        fields = ['detail']


SubTaskModelFormSet = modelformset_factory(
    SubTask,
    fields=('detail',),
    extra=1,
    widgets={'detail': forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Create subtasks here'
    })}
)


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_abbrev', 'course_prof']


class ECForm(forms.ModelForm):
    class Meta:
        model = Extracurricular
        fields = ['name', 'detail', 'start_date', 'end_date', 'active']
        widgets = {
            'detail': forms.Textarea(attrs={'cols': 35, 'rows': 2}),
            'start_date': DatePicker(attrs={'placeholder': 'yyyy-mm-dd',
                                            'append': 'fa fa-calendar',
                                            'icon_toggle': True, },
                                     options={'useCurrent': True,
                                              'collapse': True, }
                                     ),
            'end_date': DatePicker(attrs={'placeholder': 'yyyy-mm-dd',
                                          'append': 'fa fa-calendar',
                                          'icon_toggle': True, },
                                   options={'useCurrent': True,
                                            'collapse': True, }
                                   ),
        }


class DayForm(forms.Form):
    date = forms.DateField(widget = DatePicker(attrs={'placeholder': 'yyyy-mm-dd',
                                          'append': 'fa fa-calendar',
                                          'icon_toggle': True, },
                                   options={'useCurrent': True,
                                            'collapse': True, }))

    def __str__(self):
        # https://stackoverflow.com/questions/19901410/django-how-to-get-value-from-charfield-and-modelchoicefield
        day = self.cleaned_data['date'].strftime("%d")
        month = self.cleaned_data['date'].strftime("%b")
        year = self.cleaned_data['date'].strftime("%Y")
        
        return "/day/" + year + "/" + month + "/" + day


class WeekForm(forms.Form):
    
    today = date.today()
    date = forms.DateField(widget = DatePicker(attrs={'placeholder': 'yyyy-mm-dd',
                                          'append': 'fa fa-calendar',
                                          'icon_toggle': True, },
                                   options={'useCurrent': True,
                                            'collapse': True, }))

    def __str__(self):
        #2020/week/17
        week = self.cleaned_data['date'].strftime("%W")
        year = self.cleaned_data['date'].strftime("%Y")
        
        return "/" + year + "/week/" + week


class MonthForm(forms.Form):
    JAN = 'Jan'
    FEB = 'Feb'
    MAR = 'Mar'
    APR = 'Apr'
    MAY = 'May'
    JUN = 'Jun'
    JUL = 'Jul'
    AUG = 'Aug'
    SEP = 'Sep'
    OCT = 'Oct'
    NOV = 'Nov'
    DEC = 'Dec'

    MONTH_CHOICES = [
        (JAN, 'Jan'),
        (FEB, 'Feb'),
        (MAR, 'Mar'),
        (APR, 'Apr'),
        (MAY, 'May'),
        (JUN, 'Jun'),
        (JUL, 'Jul'),
        (AUG, 'Aug'),
        (SEP, 'Sep'),
        (OCT, 'Oct'),
        (NOV, 'Nov'),
        (DEC, 'Dec'),
    ]
    month = forms.ChoiceField(choices=MONTH_CHOICES)
    year = forms.CharField(max_length=4)  # add default to be current year
    # returns the custom url for the redirect

    def __str__(self):
        # https://stackoverflow.com/questions/19901410/django-how-to-get-value-from-charfield-and-modelchoicefield
        return "/month/" + self.cleaned_data['year'] + "/" + self.cleaned_data['month']

todo/templates/todo/completed_list.html
{% extends 'todo/list_base.html' %}

{% block filter %}

<div class="row">
  <div class="col">
    <h4>Completed to-do items</h4>
  </div>
</div>

{% endblock %}

todo/templates/todo/list_base.html
{% extends 'todo/base.html' %}

<!-- https://stackoverflow.com/questions/11481499/django-iterate-number-in-for-loop-of-a-template-->

{% block content %}

{% block filter %}{% endblock %} <!-- where titles will be-->

<div class="row">
  <div class="d-none d-lg-inline" id="notes">
    <header id="notes-header">
      <span id="notes-title">
      Notes Area
      </span>
    </header>
    <form action="{% url 'todo_list:notes' %}" method="post">
      {% csrf_token %}
      <label for="notes-text"></label>
      <textarea type="text" name="notes" id="notes-text">{{note}}</textarea>
      <button type="submit" class="btn btn-success btn-sm" value="Submit" >Save</button>
    </form>
  </div>

  <div class="col">
    <div class="d-flex justify-content-center">
      {% if todo_list %}
      <ul class="w-md-65 list-group">
        <div id="accordion">
          <!-- accordion is the template for collapsing bars -->
          {% for todo_item in todo_list %}
            <div class="card">
              <button
                class="btn collapsed"
                id="cardButton"
                data-toggle="collapse"
                data-target="#collapse{{forloop.counter}}"
              >
                <li class="list-group-item">
                  {% if todo_item.priority == "HI" and not todo_item.completed %}
                  <div class="card-header border border-danger" id="header{{forloop.counter}}">
                  {% elif todo_item.priority == "MD" and not todo_item.completed %}
                  <div class="card-header border border-warning" id="header{{forloop.counter}}">
                  {% else %}
                  <div class="card-header border bg-light" id="header{{forloop.counter}}">
                  {% endif %}
                    <p class="d-flex justify-content-start">
                      {% if not todo_item.completed %}
                        {{todo_item.title}}
                      {% else %}
                        <del>{{todo_item.title}}</del>
                      {% endif %}
                    </p>

                    <div class="d-flex justify-content-around mt-3">
                      {% if todo_item.completed %}
                        <small><i>Task Completed!</i></small>
                      {% elif todo_item.is_past_due %}
                        <small><i style="color:red">Past due!</i></small>
                      {% endif %}
                      <small>due {{todo_item.duedate}}</small>
                    </div>
                  </div>

                  {% if todo_item.progress %}
                    {% if not todo_item.completed %}
                      <div class="progress" style="margin-top:3px;">
                        <div class="progress-bar bg-info" role="progressbar" style="width: {{todo_item.progress}}%;" aria-valuenow="{{todo_item.progress}}"
                              aria-valuemin="0" aria-valuemax="100">{{todo_item.progress}}% completed!</div>
                      </div>
                    {% endif %}
                {% endif %}
                </li>
              </button>
              
              <!--forloop.counter gives each instance of todo_item a different id so each box collapses independently of each other -->
              <div id="collapse{{forloop.counter}}" class="collapse">
                <!--body of the accordion card -->
                <div class="card-body">
                  <ul style="list-style-type:none">
                    {% if todo_item.description %}
                    <li>
                      <strong>Description:</strong> {{ todo_item.description }}
                    </li>
                    {% endif %} {% if todo_item.location %}
                    <li><strong>Location:</strong> {{ todo_item.location }}</li>
                    {% endif %}
                    {% if todo_item.recur_freq != 'NEVER' %}
                      <li><strong>Repeat:</strong> {{ todo_item.recur_freq }}</li>
                      <li>
                        <strong>End repeat:</strong> {{ todo_item.end_recur_date }}</li>
                    {% endif %}
                    {% if todo_item.category != 'NN' %}
                      <li><strong>Category:</strong> {{ todo_item.get_category_display }}</li>
                      {% if todo_item.category == 'AC' %}
                        {% if todo_item.course %}
                          <li><strong>Course:</strong> {{ todo_item.course }}</li>
                        {% endif %}
                      {% elif todo_item.category == 'EC' %}
                        {% if todo_item.ec %}
                          <li><strong>Activity:</strong> {{ todo_item.ec }}</li>
                        {% endif %}
                      {% endif %}
                    {% endif %}
                  </ul>
                  {% if todo_item.subtask_set.all %}
                  <ul>
                    {% for subtask in todo_item.subtask_set.all %}
                      {% if not subtask.completed %}
                        <li>
                          <a href="{% url 'todo_list:complete_subtask' subtask.id %}">
                            {{ subtask }}</a>
                        </li>
                      {% else %}
                        <li>
                          <a href="{% url 'todo_list:complete_subtask' subtask.id %}">
                            <del>{{ subtask }}</del></a>
                        </li>
                      {% endif %}
                    {% endfor %}
                  </ul>
                  {% endif %}
                  <div class="row m-sm-3">
                    <div>
                      {% if not todo_item.completed %}
                      <small><a
                        class="text-success" href="{% url 'todo_list:complete_todo' todo_item.id %}"
                        >✅ Complete Task</a
                      ></small>
                      {% else %}
                      <small><a
                        href="{% url 'todo_list:complete_todo' todo_item.id %}"
                      >Undo completion</a></small>
                      {% endif %}
                    </div>
                    <div class="ml-auto">
                      <small class="m-2"
                        ><a href="{% url 'todo_list:add_subtask' todo_item.id %}"
                          >+ Add subtasks</a
                        ></small>
                      <small class="m-2"
                        ><a href="{% url 'todo_list:detail' todo_item.id %}"
                          >🖊 Edit</a
                        ></small
                      >
                      <small><a
                        class="text-danger" href="{% url 'todo_list:delete_todo_item' todo_item.id %}"
                        >🗑 Delete</a
                      ></small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </ul>
      {% else %}
        {% block gifs %}{% endblock %}
        <p>You have nothing to do!</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

todo/templates/todo/social_list.html
{% extends 'todo/list_base.html' %}

{% block filter %}

<div class="row">
  <div class="col">
    <div class="row">
      <h4 style="margin-bottom:10px;">Social</h4>
    </div>

    <div class="row" style="margin-bottom:10px;">
      <div class="dropdown">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="filterDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Filter by Category
        </button>
        <div class="dropdown-menu" aria-labelledby="filterDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:academics_list' %}"
            >Academics</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:ec_todo_list' %}"
            >Extracurriculars</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:job_list' %}">Job</a>
          <a class="dropdown-item" href="{% url 'todo_list:social_list' %}"
            >Social</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:personal_list' %}"
            >Personal</a
          >
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'todo_list:other_list' %}"
            >Other</a
          >
    </div>
  </div>


  <div class="col">
  </div>
  <div class="col">
  </div>
  <div class="col">
  </div>
  <div class="col">
  </div><div class="col">
  </div>

  <div class="col">
    <div class="row">
      <div class="dropdown">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="filterDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Filter by Today
        </button>
        <div class="dropdown-menu" aria-labelledby="filterDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:social_today_todo_list' %}"
            >Today</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

todo/templates/todo/todoitem_archive_day.html
{% extends 'todo/list_base.html' %}

{% block filter %}

<div class="row">
  <div class="d-flex justify-content-center">
    <h4>To-do items due on {{ day }}</h4>
  </div>
  <div class="col" style="margin-bottom:5px;">
    <div class="d-flex justify-content-center">
      <a href="/day/{{previous_day.year}}/{{previous_day|date:'b'}}/{{previous_day.day}}/" class="btn btn-outline-secondary" style="margin-top:5px;">Previous day</a>
      <a href="/day/{{next_day.year}}/{{next_day|date:'b'}}/{{next_day.day}}/" class="btn btn-outline-secondary" style="margin-top:5px;">Next day</a>
    </div>
  </div>
</div>

<div class="row mb-4">
  <div clas="col">
    <div class="d-flex justify-content-start col-6">
      <div class="dropdown" style="margin-right: 5px;">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="filterDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Filter by Category
        </button>
        <div class="dropdown-menu" aria-labelledby="filterDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:academics_list' %}"
            >Academics</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:ec_todo_list' %}"
            >Extracurriculars</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:job_list' %}">Job</a>
          <a class="dropdown-item" href="{% url 'todo_list:social_list' %}"
            >Social</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:personal_list' %}"
            >Personal</a
          >
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'todo_list:other_list' %}"
            >Other</a
          >
        </div>
      </div>
  
      <div class="dropdown">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="viewDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          View by Dates
        </button>
        <div class="dropdown-menu" aria-labelledby="viewDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:archive_today' %}">
            Today
          </a>
          <a class="dropdown-item" href="/{% now "Y" %}/week/{% now "W" %}">
            This week
          </a>
          <a class="dropdown-item" href="{% url 'todo_list:specific_month' year=1 month='curr' %}">
            This month
          </a>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <a href="{% url 'todo_list:day' %}" type="button" class="btn btn-outline-secondary">Specific day</a>
    </div>
    
  </div>
  
</div>

{% endblock %}

todo/templates/todo/todoitem_archive_week.html
{% extends 'todo/list_base.html' %}

{% block filter %}

<div class="row">
  <div class="d-flex justify-content-center">
    <h4>To-do items due during the week of {{week|date:"D"}}, {{ week }}</h4>
  </div>
  <div class="col" style="margin-bottom:5px;">
    <div class="d-flex justify-content-center">
      <a href="/{{previous_week.year}}/week/{{previous_week|date:"W"}}/" class="btn btn-outline-secondary" style="margin-top:5px;">Previous week</a>
      <a href="/{{next_week.year}}/week/{{next_week|date:"W"}}/" class="btn btn-outline-secondary" style="margin-top:5px;">Next week</a>
    </div>
  </div>
</div>

<div class="row mb-4">
  <div clas="col">
    <div class="d-flex justify-content-start col-6">
      <div class="dropdown" style="margin-right: 5px;">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="filterDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Filter by Category
        </button>
        <div class="dropdown-menu" aria-labelledby="filterDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:academics_list' %}"
            >Academics</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:ec_todo_list' %}"
            >Extracurriculars</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:job_list' %}">Job</a>
          <a class="dropdown-item" href="{% url 'todo_list:social_list' %}"
            >Social</a
          >
          <a class="dropdown-item" href="{% url 'todo_list:personal_list' %}"
            >Personal</a
          >
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'todo_list:other_list' %}"
            >Other</a
          >
        </div>
      </div>
  
      <div class="dropdown">
        <button
          class="btn btn-sm btn-outline-secondary dropdown-toggle"
          href="#"
          id="viewDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          View by Dates
        </button>
        <div class="dropdown-menu" aria-labelledby="viewDropdown">
          <a class="dropdown-item" href="{% url 'todo_list:archive_today' %}">
            Today
          </a>
          <a class="dropdown-item" href="/{% now "Y" %}/week/{% now "W" %}">
            This week
          </a>
          <a class="dropdown-item" href="{% url 'todo_list:specific_month' year=1 month='curr' %}">
            This month
          </a>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <a href="{% url 'todo_list:week' %}" type="button" class="btn btn-outline-secondary">Specific week</a>
    </div>
    
  </div>
</div>

{% endblock %}